spring.application.name=tasks

api.auth.url=https://tasks.amlgroup.com.br/auth/login?page=/
api.auth.usuario=kaue.moraes@amlconsulting.com.br
api.auth.senha=220420M@nu

tasks.url.cadastrar=https://tasks.amlgroup.com.br/tarefa/incluir

server.port=8081